import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#f4f1ea",
        surface: "#f4f1ea",
        "surface-container": "#e8e6e1",
        "surface-container-high": "#dddad3",
        "surface-container-highest": "#d2cfc8",
        "surface-variant": "#e8e6e1",
        "surface-container-low": "#f7f5f0",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dedbd4",
        "surface-bright": "#f4f1ea",
        "on-surface": "#1c1c1c",
        "on-surface-variant": "#6b6860",
        "inverse-surface": "#1c1c1c",
        "inverse-on-surface": "#f4f1ea",
        outline: "#d4d0c8",
        "outline-variant": "#e8e6e1",
        primary: "#c23b22",
        "on-primary": "#ffffff",
        "primary-container": "#faddd6",
        "on-primary-container": "#5a1a0e",
        "inverse-primary": "#c23b22",
        secondary: "#2a3d66",
        "on-secondary": "#ffffff",
        "secondary-container": "#d4dbe8",
        "on-secondary-container": "#0f1a30",
        tertiary: "#765b00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#fadd93",
        "on-tertiary-container": "#3d2f00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#faddd6",
        "primary-fixed-dim": "#f0b8ab",
        "on-primary-fixed": "#5a1a0e",
        "on-primary-fixed-variant": "#8a2e1a",
        "secondary-fixed": "#d4dbe8",
        "secondary-fixed-dim": "#a9b6d0",
        "on-secondary-fixed": "#0f1a30",
        "on-secondary-fixed-variant": "#1f3055",
        "tertiary-fixed": "#fadd93",
        "tertiary-fixed-dim": "#e7c365",
        "on-tertiary-fixed": "#3d2f00",
        "on-tertiary-fixed-variant": "#594400",
        "surface-tint": "#c23b22",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "container-max": "1400px",
        "bento-gap": "24px",
        gutter: "24px",
        margin: "40px",
      },
      fontFamily: {
        h2: ["var(--font-inter)"],
        "label-vertical": ["var(--font-space-grotesk)"],
        "body-md": ["var(--font-manrope)"],
        h1: ["var(--font-inter)"],
        "body-lg": ["var(--font-manrope)"],
        "display-xl": ["var(--font-inter)"],
      },
      fontSize: {
        h2: ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-vertical": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "500" },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        h1: ["clamp(2.5rem, 4vw, 4rem)", { lineHeight: "1.15", letterSpacing: "-0.03em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-xl": [
          "clamp(5rem, 12vw, 12rem)",
          { lineHeight: "1.05", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
